import Head from 'next/head';
import "../../public/assets/css/plugins/swiper.min.css";
import "../../public/assets/css/plugins/fontawesome-5.css";
import "../../public/assets/css/plugins/animate.min.css";
import "../../public/assets/css/plugins/unicons.css";

import "../../public/assets/css/vendor/bootstrap.min.css";
import "../../public/assets/css/style.css";
import Script from 'next/script';


export const metadata = {
  title: "Finbiz Business Consulting NextJs Template",
  description: "Generated by create next app",
  icons: {
    icon: "assets/images/fav.png", // Ensure the path is correct
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Finbiz Business Consulting NextJs Template</title>
        <meta name="author" content="themewant" />
        <meta name="description" content="Finbiz Business Consulting NextJs Template" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/images/fav.png" />
      </Head>
      <body className='index-one'
      suppressHydrationWarning
      >
            
        {children}

      </body>
    </html>
  );
}
